apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
spec:
  version: v1.26.2
  namespace: istio-cni
---
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: agentic-mesh
spec:
  version: v1.26.2
  namespace: istio-system
  values:
    global:
      istioNamespace: istio-system
    pilot:
      env:
        PILOT_ENABLE_STATUS: "true"
    meshConfig:
      accessLogFile: /dev/stdout
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
      defaultConfig:
        tracing:
          sampling: 100
